In [2]:
import torch

# set seed
torch.manual_seed(1)
def tanhfunc(x):
    return (torch.exp(x)-torch.exp(-x))/(torch.exp(x)+torch.exp(-x))
def sigmoid(x):
    return 1 / (1 + torch.exp(-x))
# convert X matrix to tensor
X = torch.tensor([[1., 2., 3.], [4., 5., 6.]])

# define neural network architecture
inputlayer = X.shape[1]
hiddenlayer = 50
outputlayer = 1


hw = torch.randn(inputlayer, hiddenlayer)


hb = torch.zeros(hiddenlayer)

# define weights for output layer
ow = torch.randn(hiddenlayer, outputlayer)

# define bias for output layer
ob = torch.zeros(outputlayer)

# define activation functions




# perform forward propagation
hiddenfunc = tanhfunc(torch.matmul(X, hw) + hb)
outputfunc = sigmoid(torch.matmul(hiddenfunc, ow) + ob)

print(outputfunc)

tensor([[0.9997],
        [0.9976]])


In [3]:
import torch

# set seed
torch.manual_seed(190401086)
def tanhfunc(x):
    return (torch.exp(x)-torch.exp(-x))/(torch.exp(x)+torch.exp(-x))
def sigmoid(x):
    return 1 / (1 + torch.exp(-x))
# convert X matrix to tensor
X = torch.tensor([[1., 2., 3.], [4., 5., 6.]])

# define neural network architecture
inputlayer = X.shape[1]
hiddenlayer = 50
outputlayer = 1


hw = torch.randn(inputlayer, hiddenlayer)


hb = torch.zeros(hiddenlayer)

# define weights for output layer
ow = torch.randn(hiddenlayer, outputlayer)

# define bias for output layer
ob = torch.zeros(outputlayer)

# define activation functions




# perform forward propagation
hiddenfunc = tanhfunc(torch.matmul(X, hw) + hb)
outputfunc = sigmoid(torch.matmul(hiddenfunc, ow) + ob)

print(outputfunc)

tensor([[0.9490],
        [0.9751]])


# Yeni Bölüm

In [ ]:
hw,hb,ow,ob

(tensor([[ 0.2858, -0.9093, -0.4658,  1.4290,  1.2119, -1.2641,  0.8637,  0.5497,
          -0.2130, -0.0618,  0.4604,  0.7826,  0.2334,  0.3030, -0.1911,  0.4557,
          -0.4866,  0.5272,  0.3336, -1.0165,  2.1245, -1.0818, -1.7988, -0.7912,
           0.1679, -1.4211,  0.3764, -0.9346, -1.3235, -1.1551, -1.0001,  1.3161,
          -0.0053, -1.1514,  0.4603, -1.1152, -1.2061, -0.4533,  1.1832, -0.5047,
          -1.8111,  1.6853, -0.6082, -2.1819, -1.6261,  1.0609,  0.6371,  2.1604,
           0.7778,  0.2191],
         [-0.8497,  0.0452,  2.9281, -0.9022, -1.4959, -1.4619, -0.5387, -0.3017,
           0.3657,  0.3676, -0.5422, -0.5985, -0.0133, -0.3645, -1.2347,  0.0612,
           2.6270, -0.4922, -0.1055,  1.4811, -1.3774,  1.6607,  0.3553,  0.9143,
           0.6924, -0.8436,  0.1817, -1.1281, -1.2374,  0.5308, -1.8122,  0.6107,
          -1.0773,  0.5218,  0.2633,  0.4532, -1.3385,  0.8024, -2.5145, -2.1248,
           0.4073,  1.2016,  1.7781,  1.1294,  2.4989,  0.8083, -0.61